apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: hello
    zone: prod
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-cntr
        image: ketangote/helloworld:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
