apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: microserviceworkshop
  labels:
    app: hello
    zone: prod
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-cntr
        image: ketangote/helloworld:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
