apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: microservice-preset
  namespace: microserviceworkshop
spec:
  selector:
    matchLabels:
      applayer: backend
  env:
    - name: DB_PORT
      value: "6379"

