apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productms-destination-rules
  namespace: microserviceworkshop    
spec:
  host: productms-svc.microserviceworkshop.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2