apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-pod
  namespace: microserviceworkshop
  labels:
    app: hello
    zone: prod
    version: v1
spec:
  replicas: 2
  selector:
    app: hello      
  spec:
    containers:
    - name: hello-cntr
      image: ketangote/helloworld:latest
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8080