apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: microserviceworkshop
  labels:
    app: hello
    zone: prod
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-cntr
        image: ketangote/helloworld:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
        readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 90
      
