apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: microserviceworkshop
  labels:
    app: hello-svc
spec:
  selector:
    app: hello
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 8080
